apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html
        configMap:
          name: app1-html
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app1-html
  namespace: default
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <title>App 1</title>
      <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body {
          font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
          background: linear-gradient(135deg, #1e3a5f 0%, #2d5a7b 100%);
          color: #fff;
          min-height: 100vh;
          display: flex;
          flex-direction: column;
        }
        header {
          background: #0f2744;
          padding: 20px;
          display: flex;
          align-items: center;
          gap: 20px;
        }
        .logo {
          width: 60px;
          height: 60px;
        }
        h1 {
          font-size: 2.5rem;
          font-weight: 300;
          letter-spacing: 2px;
        }
        main {
          flex: 1;
          display: flex;
          align-items: center;
          justify-content: center;
          padding: 40px;
        }
        .content {
          background: rgba(255,255,255,0.1);
          backdrop-filter: blur(10px);
          padding: 60px;
          border-radius: 10px;
          text-align: center;
          max-width: 600px;
        }
        .content h2 {
          font-size: 3rem;
          margin-bottom: 30px;
          font-weight: 300;
        }
        .info {
          background: rgba(0,0,0,0.3);
          padding: 20px;
          border-radius: 5px;
          margin-top: 30px;
          text-align: left;
        }
        .info p {
          padding: 10px 0;
          border-bottom: 1px solid rgba(255,255,255,0.1);
        }
        .info p:last-child { border: none; }
        .label { color: #8ab4f8; font-weight: 600; }
      </style>
    </head>
    <body>
      <header>
        <svg class="logo" viewBox="0 0 32 32" xmlns="http://www.w3.org/2000/svg">
          <path fill="#326ce5" d="M16 2.5l-1.5 1.5v5.4l-4.5 2.6-4.6-2.6V4.5L4 3l-2 2v7.5l6.3 3.6v7.4l1.7 1.5 6-3.5 6 3.5 1.7-1.5v-7.4L30 12.5V5l-2-2-1.4 1.5v4.9l-4.6 2.6-4.5-2.6V3.5L16 2.5z"/>
        </svg>
        <h1>kubernetes</h1>
      </header>
      <main>
        <div class="content">
          <h2>Hello from app1.</h2>
          <div class="info">
            <p><span class="label">pod:</span> <span id="pod">Loading...</span></p>
            <p><span class="label">node:</span> <span id="node">Loading...</span></p>
          </div>
        </div>
      </main>
      <script>
        // Generar ID único de pod
        document.getElementById('pod').textContent = 'app-one-' + Math.random().toString(36).substr(2, 9);
        document.getElementById('node').textContent = 'Linux (' + navigator.platform + ')';
      </script>
    </body>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  name: app1-service
  namespace: default
spec:
  selector:
    app: app1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80