Vagrant.configure(2) do |config|
  config.vm.box = "generic/ubuntu2204"
  config.vm.synced_folder ".", "/vagrant"

  config.vm.define "jainavasS" do |machine|
    machine.vm.hostname = "jainavasS"
    machine.vm.network "private_network", ip: "192.168.56.110"
    
    machine.vm.provider "libvirt" do |libvirt|
      libvirt.memory = 1024
      libvirt.cpus = 1
    end
    
	machine.vm.provision "shell", path: "scripts/setup.sh"
	machine.vm.provision "shell", path: "scripts/deploy.sh"
  end
end
