Vagrant.configure(2) do |config|
  config.vm.box = "generic/ubuntu2204"

  config.vm.define "jainavasS" do |server|
    server.vm.hostname = "jainavasS"
    server.vm.network "private_network", ip: "192.168.56.110"
    
    server.vm.provider "libvirt" do |libvirt|
      libvirt.memory = 1024
      libvirt.cpus = 1
    end
    
    server.vm.provision "shell", path: "scripts/server-setup.sh"
  end

  config.vm.define "jainavasSW" do |worker|
    worker.vm.hostname = "jainavasSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    
    worker.vm.provider "libvirt" do |libvirt|
      libvirt.memory = 1024
      libvirt.cpus = 1
    end
    
    worker.vm.provision "shell", path: "scripts/agent-setup.sh"
  end
end